stages:
  - lint
  - format
  - type_check
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -m pip install --upgrade pip
  - python -m pip install ruff mypy pytest streamlit requests vulture bandit pip-audit

lint_job:
  stage: lint
  script:
    - python -m ruff check .

format_job:
  stage: format
  script:
    - python -m ruff format --check .

type_check_job:
  stage: type_check
  script:
    - python -m mypy . --ignore-missing-imports

test_job:
  stage: test
  script:
    - python -m pytest